WebBilling/Models/Invoices.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Web;

namespace WebInvoicing.Models
{
    public class Invoices
    {
        public int ID { get; set; }

        [Display(Name = "Customer")]
        public string customerID { get; set; }
        public virtual UserAccount customer { get; set; }

        [Display(Name = "Invoice #")]
        public string name { get; set; }

        [Display(Name = "Date")]
        [DataType(DataType.Date)]
        public DateTime date { get; set; }

        [Display(Name = "Mark as paid")]
        public bool paid { get; set; }

        public int PDFFileID { get; set; }
        public virtual PDFFile PDFFile { get; set; }
    }
}

WebBilling/Controllers/InvoicesController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Threading.Tasks;
using System.Net;
using System.Web;
using System.Web.Mvc;
using WebInvoicing.Models;
using CSGOSideLoungeMVCTest4.DAL;
using WebInvoicing.ActiveDirectoryHelpers;

namespace WebBilling.Controllers
{
    public class InvoicesController : Controller
    {
        private CompXDbContext db = new CompXDbContext();

        // GET: /Invoices/
        public async Task<ActionResult> Index(string account, string time)
        {
            //only show your own invoices past 3 months, 90 days
            DateTime cutoffDate = DateTime.Now.Subtract(new TimeSpan(90, 0, 0, 0));
            var invoices = db.Invoices.Where(i => i.customerID.ToLower() == User.Identity.Name.ToLower()).Include(i => i.PDFFile);
            if (string.IsNullOrWhiteSpace(time))
            {
                //then use cutoff date
                invoices = invoices.Where(i => i.date > cutoffDate);
            }
            else
                ViewBag.time = "all";
            if (LDAPHelper.UserIsMemberOfGroupOC("Boss", User.Identity.Name) || LDAPHelper.UserIsMemberOfGroupOC("Admins", User.Identity.Name))
            {
                if (string.IsNullOrWhiteSpace(account))
                    invoices = db.Invoices.Include(i => i.PDFFile);
                else
                    invoices = db.Invoices.Where(i => i.customerID.ToLower() == account.ToLower()).Include(i => i.PDFFile);
            }
            return View(await invoices.ToListAsync());
        }

        // GET: /Invoices/Details/5
        public async Task<ActionResult> Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Invoices invoices = await db.Invoices.FindAsync(id);
            if (invoices == null)
            {
                return HttpNotFound();
            }
            return View(invoices);
        }

        // GET: /Invoices/Create
        [AuthorizeAD(Groups = "Boss,Admins")]
        public ActionResult Create()
        {
            ViewBag.PDFFileID = new SelectList(db.PDFFiles, "ID", "ID");
           // List<UserAccount> customers = db.UserAccounts.ToList().Where(ua => ua.permissionGroup == "Customer").ToList();
            ViewBag.customerID = new SelectList(db.UserAccounts.ToList().Where(ua => ua.permissionGroup == "Customer"), "userName", "userName").OrderBy(c => c.Text);
            return View();
        }

        // POST: /Invoices/
        [HttpPost]
        public async Task<ActionResult> ChangePaid(int id, bool value)
        {
            Invoices invoices = await db.Invoices.FindAsync(id);
            if (invoices == null)
            {
                return Json(new { Success = false });
            }
            invoices.paid = value;
            db.Entry(invoices).State = EntityState.Modified;
            await db.SaveChangesAsync();
            return Json(new { Success = true });
        }

        // POST: /Invoices/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [AuthorizeAD(Groups = "Boss,Admins")]
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<ActionResult> Create([Bind(Include = "ID,customerID,name,date,paid")] Invoices invoices, HttpPostedFileBase upload)
        {
            if (ModelState.IsValid)
            {
                if (upload != null && upload.ContentLength > 0 && upload.FileName.EndsWith(".pdf"))
                {
                    var pdf = new PDFFile();
                    using (var reader = new System.IO.BinaryReader(upload.InputStream))
                    {
                        pdf.Content = reader.ReadBytes(upload.ContentLength);
                    }
                    db.PDFFiles.Add(pdf);
                    invoices.PDFFileID = pdf.ID;
                }
                db.Invoices.Add(invoices);
                await db.SaveChangesAsync();
                return RedirectToAction("Index");
            }

            ViewBag.PDFFileID = new SelectList(db.PDFFiles, "ID", "ID", invoices.PDFFileID);
            ViewBag.customerID = new SelectList(db.UserAccounts.ToList().Where(ua => ua.permissionGroup == "Customer"), "userName", "userName").OrderBy(c => c.Text);
            return View(invoices);
        }

        // GET: /File/
        public async Task<ActionResult> PDFFile(int id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Invoices invoices = await db.Invoices.FindAsync(id);
            if (invoices == null || invoices.PDFFileID == null)
            {
                return HttpNotFound();
            }
            if (LDAPHelper.UserIsMemberOfGroupOC("Boss", User.Identity.Name) || LDAPHelper.UserIsMemberOfGroupOC("Admins", User.Identity.Name) || invoices.customerID.ToLower() == User.Identity.Name.ToLower())
            {
                var fileToRetrieve = db.PDFFiles.Find(invoices.PDFFileID);
                if (fileToRetrieve == null)
                {
                    return HttpNotFound();
                }
                return File(fileToRetrieve.Content, "application/pdf", "Computrex_Invoice" + invoices.name + ".pdf");
            }
            else
                return HttpNotFound();
        }

        // GET: /Invoices/Edit/5
        [AuthorizeAD(Groups = "Boss,Admins")]
        public async Task<ActionResult> Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Invoices invoices = await db.Invoices.FindAsync(id);
            if (invoices == null)
            {
                return HttpNotFound();
            }
            ViewBag.PDFFileID = new SelectList(db.PDFFiles, "ID", "ID", invoices.PDFFileID);
            return View(invoices);
        }

        // POST: /Invoices/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [AuthorizeAD(Groups = "Boss,Admins")]
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<ActionResult> Edit([Bind(Include="ID,customerID,name,date,paid,PDFFileID")] Invoices invoices)
        {
            if (ModelState.IsValid)
            {
                db.Entry(invoices).State = EntityState.Modified;
                await db.SaveChangesAsync();
                return RedirectToAction("Index");
            }
            ViewBag.PDFFileID = new SelectList(db.PDFFiles, "ID", "ID", invoices.PDFFileID);
            return View(invoices);
        }

        // GET: /Invoices/Delete/5
        [AuthorizeAD(Groups = "Boss,Admins")]
        public async Task<ActionResult> Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Invoices invoices = await db.Invoices.FindAsync(id);
            if (invoices == null)
            {
                return HttpNotFound();
            }
            return View(invoices);
        }

        // POST: /Invoices/Delete/5
        [AuthorizeAD(Groups = "Boss,Admins")]
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<ActionResult> DeleteConfirmed(int id)
        {
            Invoices invoices = await db.Invoices.FindAsync(id);
            db.Invoices.Remove(invoices);
            await db.SaveChangesAsync();
            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

WebBilling/Views/Invoices/Create.cshtml
@model WebInvoicing.Models.Invoices

@{
    ViewBag.Title = "Create Invoice";
}

<h2>Create Invoice</h2>

@using (Html.BeginForm("Create", "Invoices", null, FormMethod.Post, new { enctype = "multipart/form-data" }))
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal text18Size">
        <hr />
        @Html.ValidationSummary(true)

        <div class="form-group">
            @Html.LabelFor(model => model.customerID, new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.DropDownList("customerID", String.Empty)
                @Html.ValidationMessageFor(model => model.customerID)
            </div>
        </div>

        <div class="form-group">
            @Html.Label("Invoice # or EOM", new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.name)
                @Html.ValidationMessageFor(model => model.name)
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.paid, new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.paid)
                @Html.ValidationMessageFor(model => model.paid)
            </div>
        </div>

        <div class="form-group">
            @Html.Label("PDF Invoice File", new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                <input type="file" id="pdfFile" name="upload" accept=".pdf" />
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.date, new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                <input class="text-box single-line datecontrol" data-val="true" data-val-date="The field Date must be a date." data-val-required="The Date field is required." id="date" name="date" value="" type="date">
                @Html.ValidationMessageFor(model => model.date)
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Create" class="btn btn-info sizedButton" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Back to List", "Index")
</div>

<script src="js/bootstrap-datepicker.js"></script>
<script type="text/javascript">
    $(function () { // will trigger when the document is ready
        $('.datecontrol').datepicker(); //Initialise any date pickers
    });
</script>

WebBilling/Views/Invoices/Delete.cshtml
@model WebInvoicing.Models.Invoices

@{
    ViewBag.Title = "Delete";
}

<h2>Delete</h2>

<h3>Are you sure you want to delete this?</h3>
<div>
    <h4>Invoices</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.PDFFile.ID)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.PDFFile.ID)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.customerID)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.customerID)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.name)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.name)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.date)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.date)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.paid)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.paid)
        </dd>

    </dl>

    @using (Html.BeginForm()) {
        @Html.AntiForgeryToken()

        <div class="form-actions no-color">
            <input type="submit" value="Delete" class="btn btn-warning sizedButton"  /> |
            @Html.ActionLink("Back to List", "Index")
        </div>
    }
</div>

WebBilling/Views/Invoices/Details.cshtml
@model WebInvoicing.Models.Invoices

@{
    ViewBag.Title = "Details";
}

<h2>Details</h2>

<div>
    <h4>Invoices</h4>
	<hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.PDFFile.ID)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.PDFFile.ID)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.customerID)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.customerID)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.name)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.name)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.date)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.date)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.paid)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.paid)
        </dd>

    </dl>
</div>
<p>
    @Html.ActionLink("Edit", "Edit", new { id = Model.ID }) |
    @Html.ActionLink("Back to List", "Index")
</p>

WebBilling/Views/Invoices/Edit.cshtml
@model WebInvoicing.Models.Invoices

@{
    ViewBag.Title = "Edit";
}

<h2>Edit</h2>

@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal">
        <h4>Invoices</h4>
        <hr />
        @Html.ValidationSummary(true)
        @Html.HiddenFor(model => model.ID)

        <div class="form-group">
            @Html.LabelFor(model => model.customerID, new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.customerID)
                @Html.ValidationMessageFor(model => model.customerID)
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.name, new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.name)
                @Html.ValidationMessageFor(model => model.name)
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.date, new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.date)
                @Html.ValidationMessageFor(model => model.date)
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.paid, new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.paid)
                @Html.ValidationMessageFor(model => model.paid)
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.PDFFileID, "PDFFileID", new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.DropDownList("PDFFileID", String.Empty)
                @Html.ValidationMessageFor(model => model.PDFFileID)
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Save" class="btn btn-default" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Back to List", "Index")
</div>

WebBilling/Views/Invoices/Index.cshtml
@model IEnumerable<WebInvoicing.Models.Invoices>
@using Microsoft.AspNet.Identity

@{
    ViewBag.Title = "Invoices";
}

@if (!LDAPHelper.UserIsMemberOfGroup("Customer"))
{
    <h2>Invoices</h2>
}
else
{
    <h2>@Html.Raw(User.Identity.GetUserName())'s invoices</h2>
}

<p>
    <table style="width: 90%; min-width: 630px;">
        <tr>
            <td>
                @if (LDAPHelper.UserIsMemberOfGroup("Boss") || LDAPHelper.UserIsMemberOfGroup("Admins"))
                {
                    <button class="btn btn-success sizedButton invoiceTableIndexBtn" onclick="location.href='@Url.Action("Create", "Invoices")';return false;">Create New Invoice</button>
                }
            </td>
            @if (LDAPHelper.UserIsMemberOfGroup("Customer"))
            {
             
            <td>
                @if (ViewBag.time == null)
                {
                    @Html.ActionLink("Past 3 Months", "Index", new { }, new { @class = "a-InvoiceTypesSelected" });
                }
                else
                {
                    @Html.ActionLink("Past 3 Months", "Index", new { }, new { @class = "a-InvoiceTypes" });
                }
            </td>
            <td>
                @if (ViewBag.time != null)
                {
                    @Html.ActionLink("All Time", "Index", new { time = "all" }, new { @class = "a-InvoiceTypesSelected" })
                }
                else
                {
                    @Html.ActionLink("All Time", "Index", new { time = "all" }, new { @class = "a-InvoiceTypes" })
                }
            </td>
            }
        </tr>
    </table>
</p>
<table class="table text18Size" style="min-width: 700px;">
    <tr>
        @if (!LDAPHelper.UserIsMemberOfGroup("Customer"))
        { 
            <th>
                @Html.DisplayNameFor(model => model.customerID)
            </th>
        }
        <th>
            PDF File
        </th>
        <th>
            @Html.DisplayNameFor(model => model.name)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.date)
        </th>
        @if (LDAPHelper.UserIsMemberOfGroup("Customer"))
        { 
            <th>
                @Html.DisplayNameFor(model => model.paid)
            </th>
        }
        <th></th>
    </tr>

@foreach (var item in Model) {
    <tr>
        @if (!LDAPHelper.UserIsMemberOfGroup("Customer"))
        {
            <td>
                @Html.DisplayFor(modelItem => item.customerID)
            </td>
        }
        <td>
            @Html.ActionLink("View Invoice", "PDFFile", new { id = item.ID }, new { target = "_blank" })
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.name)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.date)
        </td>
        @if (LDAPHelper.UserIsMemberOfGroup("Customer"))
        {
            <td>
                <input class="check-box" data-val="true" name="item.paid" checked="@item.paid" type="checkbox" onchange="changePaid(this, @item.ID); return false;">
            </td>
        }
        <td>
            @if (LDAPHelper.UserIsMemberOfGroup("Boss") || LDAPHelper.UserIsMemberOfGroup("Admins"))
            {
                
                @Html.ActionLink("Delete", "Delete", new { id=item.ID })
            }
        </td>
    </tr>
}

</table>

<script>

    function changePaid(box, id) {

        $.ajax({
            url: '@Url.Action("ChangePaid", "Invoices")',
            type: 'POST',
            dataType: "json",
            data: { id: id, value: $(box).is(':checked') },
            success: function (data) {
                if (data.Success) {
                    
                }
            }
        });
    }

</script>