WebBilling/Models/UserAccount.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Web;

namespace WebInvoicing.Models
{
    public class UserAccount
    {
        [Key]
        [Display(Name = "User name")]
        public string userName { get; set; }

        [Display(Name = "Password")]
        public string hashPassword { get; set; }

        [Display(Name = "Permission group")]
        public string permissionGroup { get; set; }

        public virtual ICollection<Invoices> Invoices { get; set; }
    }
}

WebBilling/Controllers/UserAccountController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Threading.Tasks;
using System.Net;
using System.Web;
using System.Web.Mvc;
using WebInvoicing.Models;
using CSGOSideLoungeMVCTest4.DAL;
using WebInvoicing.Encryption;
using System.Web.Security;
using WebInvoicing.ActiveDirectoryHelpers;

namespace WebBilling.Controllers
{
    public class UserAccountController : Controller
    {
        private CompXDbContext db = new CompXDbContext();

        [HttpPost]
        [AllowAnonymous]
        public async Task<ActionResult> Login(string userName, string time, string hash)
        {
            if (string.IsNullOrWhiteSpace(userName) || string.IsNullOrWhiteSpace(time) || string.IsNullOrWhiteSpace(hash))
            {
                return Json(new { Success = false, error = "Invalid input" });
            }
            userName = userName.ToLower();
            DateTime hashedTime = new DateTime(1970, 1, 1, 0, 0, 0).AddMilliseconds(Convert.ToDouble(time));
            TimeSpan elapsedTime = new TimeSpan(DateTime.Now.Ticks - hashedTime.Ticks);
            if (elapsedTime.TotalSeconds > 30)
                return Json(new { Success = false, error = "Server took too long to log in. Please try again." });

            if (validateUser(userName, time, hash))
            {

                //Capitalize first letter
                string userNamestring = userName.Substring(0, 1).ToUpper() + userName.Substring(1);
                FormsAuthentication.SetAuthCookie(userNamestring, true);
                string url = Url.Action("Index", "Invoices");
                return Json(new { redirect = url });
            }

            return Json(new { Success = false, error = "The user name or password provided is incorrect." });
        }

        private bool validateUser(string userName, string time, string hash)
        {
            UserAccount acct = db.UserAccounts.Find(userName);
            if (acct == null)
                return false;
            string pass = EncryptionHelper.Decrypt(acct.hashPassword);
            string toHash = "Web_Invoicing" + time + pass;
            string ourHash = EncryptionHelper.sha256_hash(toHash);
            if (ourHash == hash)
                return true;
            else
                return false;
        }

        // GET: /UserAccount/
        [AuthorizeAD(Groups = "Boss,Admins")]
        public async Task<ActionResult> Index()
        {
            return View(await db.UserAccounts.ToListAsync());
        }

        // GET: /UserAccount/Details/5
        [AuthorizeAD(Groups = "Boss,Admins")]
        public async Task<ActionResult> Details(string id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            UserAccount useraccount = await db.UserAccounts.FindAsync(id);
            if (useraccount == null)
            {
                return HttpNotFound();
            }
            //make password viewable if customer
            if (useraccount.permissionGroup == "Customer")
            {
                useraccount.hashPassword = EncryptionHelper.Decrypt(useraccount.hashPassword);
            }
            return View(useraccount);
        }

        // GET: /UserAccount/Create
        [AuthorizeAD(Groups = "Boss,Admins")]
        public ActionResult Create(string type)
        {
            ViewBag.type = type;
            return View();
        }

        // POST: /UserAccount/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [AuthorizeAD(Groups = "Boss,Admins")]
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<ActionResult> Create([Bind(Include="userName,hashPassword,permissionGroup")] UserAccount useraccount)
        {
            if (ModelState.IsValid)
            {
                //check that the user has sufficient priveliges
                if (useraccount.permissionGroup == "Boss" || useraccount.permissionGroup == "Admins")
                {
                    if (!LDAPHelper.UserIsMemberOfGroupOC("Boss", User.Identity.Name))
                        RedirectToAction("Error", "ErrorPages");
                }
                else //auto generate a password for the customers
                {
                    useraccount.hashPassword = System.Web.Security.Membership.GeneratePassword(9, 2);
                }
                //hash the password with the apps secret key
                useraccount.hashPassword = EncryptionHelper.Encrypt(useraccount.hashPassword);
                db.UserAccounts.Add(useraccount);
                await db.SaveChangesAsync();
                return RedirectToAction("Index");
            }

            return View(useraccount);
        }

        // GET: /UserAccount/Edit/5
        [AuthorizeAD(Groups = "Boss,Admins")]
        public async Task<ActionResult> Edit(string id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            UserAccount useraccount = await db.UserAccounts.FindAsync(id);
            if (useraccount == null)
            {
                return HttpNotFound();
            }
            if (useraccount.permissionGroup == "Boss" && !LDAPHelper.UserIsMemberOfGroupOC("Boss", User.Identity.Name))
                return HttpNotFound();
            return View(useraccount);
        }

        // POST: /UserAccount/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [AuthorizeAD(Groups = "Boss,Admins")]
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<ActionResult> Edit([Bind(Include="userName,hashPassword,permissionGroup")] UserAccount useraccount)
        {
            if (ModelState.IsValid)
            {
                UserAccount acct = await db.UserAccounts.FindAsync(useraccount.userName);
                if (acct == null)
                {
                    return HttpNotFound();
                }
                if (acct.permissionGroup == "Boss" && !LDAPHelper.UserIsMemberOfGroupOC("Boss", User.Identity.Name))
                    return HttpNotFound();
                //hash the password with the apps secret key
                useraccount.hashPassword = EncryptionHelper.Encrypt(useraccount.hashPassword);
                db.Entry(useraccount).State = EntityState.Modified;
                await db.SaveChangesAsync();
                return RedirectToAction("Index");
            }
            return View(useraccount);
        }

        // GET: /UserAccount/Delete/5
        [AuthorizeAD(Groups = "Boss,Admins")]
        public async Task<ActionResult> Delete(string id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            UserAccount useraccount = await db.UserAccounts.FindAsync(id);
            if (useraccount == null)
            {
                return HttpNotFound();
            }
            if (useraccount.permissionGroup == "Boss" && !LDAPHelper.UserIsMemberOfGroupOC("Boss", User.Identity.Name))
                return HttpNotFound();
            return View(useraccount);
        }

        // POST: /UserAccount/Delete/5
        [AuthorizeAD(Groups = "Boss,Admins")]
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<ActionResult> DeleteConfirmed(string id)
        {
            UserAccount useraccount = await db.UserAccounts.FindAsync(id);
            if (useraccount.permissionGroup == "Boss" && !LDAPHelper.UserIsMemberOfGroupOC("Boss", User.Identity.Name))
                return HttpNotFound();
            db.UserAccounts.Remove(useraccount);
            await db.SaveChangesAsync();
            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

WebBilling/Views/UserAccount/Create.cshtml
@model WebInvoicing.Models.UserAccount

@{
    ViewBag.Title = "Create User Account";
}

<h2>Create @ViewBag.type Account</h2>

@using (Html.BeginForm()) 
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal text18Size">
        
        <hr />
        @Html.ValidationSummary(true)

        <div class="form-group">
            @Html.LabelFor(model => model.userName, new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.userName)
                @Html.ValidationMessageFor(model => model.userName)
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.hashPassword, new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @if (ViewBag.type == "Admins")
                { 
                     @Html.PasswordFor(model => model.hashPassword, new { @id = "firstPassword", @oninput = "checkPassword()" })
                    @Html.ValidationMessageFor(model => model.hashPassword)
                }
                else
                {
                    @Html.Raw("Password automatically generated.");
                }
            </div>
        </div>

        <!--Password Double Check-->
        @if (ViewBag.type == "Admins")
        { 
            <div class="form-group">
                @Html.Label("Confirm password", new { @class = "control-label col-md-2" })
                <div class="col-md-10">
                    <input type="password" name="password" id="confirmPass" oninput="checkPassword()">
                </div>
            </div>

            <div class="form-group hidden" id="passError">
                @Html.Label(" ", new { @class = "control-label col-md-2" })
                <div class="col-md-10" style="color: #ff0000">
                    Passwords do not match!
                </div>
            </div>
        }
        <input type="hidden" value="@ViewBag.type" id="permissionGroup" name="permissionGroup" />

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" id="submitBtn" value="Create" class="btn btn-info sizedButton" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Back to List", "Index")
</div>

<script>

    function checkPassword() {
        if ($('#firstPassword').val() == $('#confirmPass').val()) {
            $('#passError').addClass("hidden");
            $('#submitBtn').prop('disabled', false);
        }
        else {
            $('#passError').removeClass("hidden");
            $('#submitBtn').prop('disabled', true);
        }
    }

</script>

WebBilling/Views/UserAccount/Delete.cshtml
@model WebInvoicing.Models.UserAccount

@{
    ViewBag.Title = "Delete";
}

<h2>Delete</h2>

<h3>Are you sure you want to delete this?</h3>
<div>
    <h4>UserAccount</h4>
    <hr />
    <dl class="dl-horizontal text18Size">
        <dt>
            @Html.DisplayNameFor(model => model.userName)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.userName)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.permissionGroup)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.permissionGroup)
        </dd>

    </dl>

    @using (Html.BeginForm()) {
        @Html.AntiForgeryToken()

        <div class="form-actions no-color">
            <input type="submit" value="Delete" class="btn btn-warning sizedButton" /> |
            @Html.ActionLink("Back to List", "Index")
        </div>
    }
</div>

WebBilling/Views/UserAccount/Details.cshtml
@model WebInvoicing.Models.UserAccount

@{
    ViewBag.Title = "Account Details";
}

<h2>Account Details</h2>

<div>
	<hr />
    <dl class="dl-horizontal text18Size">
        <dt>
            @Html.DisplayNameFor(model => model.userName)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.userName)
        </dd>
        @if (Model.permissionGroup == "Customer")
        {
        <dt>
            @Html.DisplayNameFor(model => model.hashPassword)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.hashPassword)
        </dd>
        }
        <dt>
            @Html.DisplayNameFor(model => model.permissionGroup)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.permissionGroup)
        </dd>

    </dl>
</div>
<p>
    @Html.ActionLink("Edit", "Edit", new { id = Model.userName }) |
    @Html.ActionLink("Back to List", "Index")
</p>

WebBilling/Views/UserAccount/Edit.cshtml
@model WebInvoicing.Models.UserAccount

@{
    ViewBag.Title = "Edit";
}

<h2>Edit Account</h2>

@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal text18Size">
 
        <hr />
        @Html.ValidationSummary(true)
        @Html.HiddenFor(model => model.userName)

        <div class="form-group">
            @Html.LabelFor(model => model.userName, new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Model.userName
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.hashPassword, new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.PasswordFor(model => model.hashPassword, new { @id = "firstPassword", @oninput = "checkPassword()" })
                @Html.ValidationMessageFor(model => model.hashPassword)
            </div>
        </div>

        <!--Password Double Check-->
        <div class="form-group">
            @Html.Label("Confirm password", new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                <input type="password" name="password" id="confirmPass" oninput="checkPassword()">
            </div>
        </div>

        <div class="form-group hidden" id="passError">
            @Html.Label(" ", new { @class = "control-label col-md-2" })
            <div class="col-md-10" style="color: #ff0000">
                Passwords do not match!
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.permissionGroup, new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                <select id="permissionGroup" name="permissionGroup">
                    <option value=""></option>
                    <option value="Admins">Admins</option>
                    <option value="Customer">Customer</option>
                </select>
                @Html.ValidationMessageFor(model => model.permissionGroup)
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" id="submitBtn" value="Save" class="btn btn-info sizedButton"  />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Back to List", "Index")
</div>

<script>

    function checkPassword() {
        if ($('#firstPassword').val() == $('#confirmPass').val()) {
            $('#passError').addClass("hidden");
            $('#submitBtn').prop('disabled', false);
        }
        else {
            $('#passError').removeClass("hidden");
            $('#submitBtn').prop('disabled', true);
        }
    }

</script>

WebBilling/Views/UserAccount/Index.cshtml
@model IEnumerable<WebInvoicing.Models.UserAccount>

@{
    ViewBag.Title = "User Accounts";
}

<h2>User Accounts</h2>

<p>
    @if (LDAPHelper.UserIsMemberOfGroup("Boss"))
    {
        <button class="btn btn-success sizedButton invoiceTableIndexBtn" onclick="location.href='@Url.Action("Create", "UserAccount", new { type = "Admins" })';return false;">Create New Admin</button>
    }
    
        <button class="btn btn-success sizedButton invoiceTableIndexBtn" onclick="location.href='@Url.Action("Create", "UserAccount", new { type = "Customer" })';return false;">Create New Customer</button>
</p>
<table class="table text18Size" style="min-width: 700px;">
    <tr>
        <th>
            @Html.DisplayNameFor(model => model.userName)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.permissionGroup)
        </th>
        <th>
            Invoices
        </th>
        <th></th>
    </tr>

@foreach (var item in Model) {
    <tr>
        <td>
            @Html.DisplayFor(modelItem => item.userName)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.permissionGroup)
        </td>
        <td>
            @if(item.permissionGroup == "Customer")
            { 
                @Html.ActionLink("View Invoices", "Index", "Invoices", new { account = item.userName }, new { })
            }
        </td>
        <td>
        @if (LDAPHelper.UserIsMemberOfGroup("Boss") || item.permissionGroup == "Customer")
        { 
            @Html.ActionLink("Edit", "Edit", new { id=item.userName }) @Html.Raw("|");
            @Html.ActionLink("Details", "Details", new { id=item.userName }) @Html.Raw("|");
            @Html.ActionLink("Delete", "Delete", new { id=item.userName })
        }
        </td>
    </tr>
}

</table>